//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanCauLong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatSan
    {
        public int MaDatSan { get; set; }
        public Nullable<int> MaSan { get; set; }
        public Nullable<int> MaNguoiChoi { get; set; }
        public Nullable<System.DateTime> NgayDatSan { get; set; }
        public Nullable<System.TimeSpan> ThoiGianBatDau { get; set; }
        public Nullable<System.TimeSpan> ThoiGianKetThuc { get; set; }
        public string TrangThai { get; set; }
    
        public virtual NguoiChoi NguoiChoi { get; set; }
        public virtual SanCauLong SanCauLong { get; set; }
    }
}
