//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanCauLong.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SanCauLongEntities1 : DbContext
    {
        public SanCauLongEntities1()
            : base("name=SanCauLongEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BinhLuan> BinhLuans { get; set; }
        public virtual DbSet<ChuSan> ChuSans { get; set; }
        public virtual DbSet<DanhGiaSan> DanhGiaSans { get; set; }
        public virtual DbSet<DatSan> DatSans { get; set; }
        public virtual DbSet<DienDan> DienDans { get; set; }
        public virtual DbSet<NguoiChoi> NguoiChois { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<SanCauLong> SanCauLongs { get; set; }
        public virtual DbSet<SuKien> SuKiens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
