//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanCauLong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuKien
    {
        public int MaSuKien { get; set; }
        public Nullable<int> MaSan { get; set; }
        public Nullable<int> MaChuSan { get; set; }
        public string TenSuKien { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string MoTa { get; set; }
        public string Images { get; set; }
    
        public virtual ChuSan ChuSan { get; set; }
        public virtual SanCauLong SanCauLong { get; set; }
    }
}
